global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3002']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3003']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:3004']

  - job_name: 'dashboard-service'
    static_configs:
      - targets: ['dashboard-service:3005']