apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudretail-config
  namespace: cloudretail
  labels:
    app: cloudretail
data:
  DB_HOST: "cloud-retail.czyg604m8g8n.ap-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "cloudretail"
  DB_TABLE_PREFIX: "sess_4bfe74e8_"
  AWS_REGION: "ap-south-1"
  API_GATEWAY_URL: "http://api-gateway.cloudretail.svc.cluster.local:3000"
  USER_SERVICE_URL: "http://user-service.cloudretail.svc.cluster.local:3001"
  PRODUCT_SERVICE_URL: "http://product-service.cloudretail.svc.cluster.local:3002"
  ORDER_SERVICE_URL: "http://order-service.cloudretail.svc.cluster.local:3003"
  INVENTORY_SERVICE_URL: "http://inventory-service.cloudretail.svc.cluster.local:3004"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
